name: Main CI

on: [push, pull_request]

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      # From https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v2

      # From https://github.com/actions/setup-python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Run flake8
      run: |
        flake8 .